export const SHOW_USERS = 'SHOW_USERS';
export const CREATE_USER = 'CREATE_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const SHOW_USERS_ERROR = 'SHOW_USERS_ERROR';
